# Generated by Django 4.2.13 on 2024-05-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="customer",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="customer's name"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="notes",
            field=models.TextField(null=True, verbose_name="additional information"),
        ),
        migrations.AddField(
            model_name="booking",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="paid"),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="total price",
            ),
        ),
    ]
