# Generated by Django 4.2.13 on 2024-05-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_customer_booking_email_booking_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="customer",
        ),
        migrations.AddField(
            model_name="booking",
            name="guest",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="guest's name"
            ),
        ),
    ]
